namespace Zakar.Common.Enums
{
    public enum SystemsSettingsEnum
    {
        MAXIMUMNUMBEROFUSERS,
        LICENSERECIPIENT,
        LICENSEPERIOD,
        MAXIMUMNUMBEROFPARTNERS,
        MAXIMUMNUMBEROFCURRENCIES,
        NOTIFICATIONSENDINGINTERVALINMINUTERS,
        DELETEQUEUEDAFTERSENDINGNOTIFICATION,
        PDFGENERATIONENABLED,
        SENDSMSUPONPARTNERCREATION
    }
}