#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using Zakar.Models;

namespace Zakar.Models	
{
	[Table("Currencies", SchemaName = "dbo")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Currency : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private int _id;
		[Column("Id", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_id")]
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _name;
		[Column("Name", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_name")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				if(this._name != value)
				{
					this.OnPropertyChanging("Name");
					this._name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}
		
		private string _symbol;
		[Column("Symbol", OpenAccessType = OpenAccessType.UnicodeStringInfiniteLength, Length = 0, Scale = 0, SqlType = "nvarchar(max)")]
		[Storage("_symbol")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if(this._symbol != value)
				{
					this.OnPropertyChanging("Symbol");
					this._symbol = value;
					this.OnPropertyChanged("Symbol");
				}
			}
		}
		
		private bool? _isDefaultCurrency;
		[Column("IsDefaultCurrency", OpenAccessType = OpenAccessType.Bit, IsNullable = true, Length = 0, Scale = 0, SqlType = "bit")]
		[Storage("_isDefaultCurrency")]
		public virtual bool? IsDefaultCurrency
		{
			get
			{
				return this._isDefaultCurrency;
			}
			set
			{
				if(this._isDefaultCurrency != value)
				{
					this.OnPropertyChanging("IsDefaultCurrency");
					this._isDefaultCurrency = value;
					this.OnPropertyChanged("IsDefaultCurrency");
				}
			}
		}
		
		private decimal _conversionRateToDefault;
		[Column("ConversionRateToDefault", OpenAccessType = OpenAccessType.Decimal, Length = 18, Scale = 2, SqlType = "decimal")]
		[Storage("_conversionRateToDefault")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual decimal ConversionRateToDefault
		{
			get
			{
				return this._conversionRateToDefault;
			}
			set
			{
				if(this._conversionRateToDefault != value)
				{
					this.OnPropertyChanging("ConversionRateToDefault");
					this._conversionRateToDefault = value;
					this.OnPropertyChanged("ConversionRateToDefault");
				}
			}
		}
		
		private IList<Partnership> _partnerships = new List<Partnership>();
		[Collection(InverseProperty = "Currency")]
		[Storage("_partnerships")]
		public virtual IList<Partnership> Partnerships
		{
			get
			{
				return this._partnerships;
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
