#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using Zakar.Models;

namespace Zakar.Models	
{
	[Table(UpdateSchema = true)]
	public partial class IdentityUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private string _id;
		[Column(IsPrimaryKey = true)]
		[Storage("_id")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _firstName;
		[Storage("_firstName")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if(this._firstName != value)
				{
					this.OnPropertyChanging("FirstName");
					this._firstName = value;
					this.OnPropertyChanged("FirstName");
				}
			}
		}
		
		private string _lastName;
		[Storage("_lastName")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if(this._lastName != value)
				{
					this.OnPropertyChanging("LastName");
					this._lastName = value;
					this.OnPropertyChanged("LastName");
				}
			}
		}
		
		private string _phoneNumber;
		[Storage("_phoneNumber")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string PhoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if(this._phoneNumber != value)
				{
					this.OnPropertyChanging("PhoneNumber");
					this._phoneNumber = value;
					this.OnPropertyChanged("PhoneNumber");
				}
			}
		}
		
		private string _userName;
		[Storage("_userName")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string UserName
		{
			get
			{
				return this._userName;
			}
			set
			{
				if(this._userName != value)
				{
					this.OnPropertyChanging("UserName");
					this._userName = value;
					this.OnPropertyChanged("UserName");
				}
			}
		}
		
		private string _passwordHash;
		[Storage("_passwordHash")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string PasswordHash
		{
			get
			{
				return this._passwordHash;
			}
			set
			{
				if(this._passwordHash != value)
				{
					this.OnPropertyChanging("PasswordHash");
					this._passwordHash = value;
					this.OnPropertyChanged("PasswordHash");
				}
			}
		}
		
		private string _securityStamp;
		[Storage("_securityStamp")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string SecurityStamp
		{
			get
			{
				return this._securityStamp;
			}
			set
			{
				if(this._securityStamp != value)
				{
					this.OnPropertyChanging("SecurityStamp");
					this._securityStamp = value;
					this.OnPropertyChanged("SecurityStamp");
				}
			}
		}
		
		private DateTime _dateCreated;
		[Storage("_dateCreated")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual DateTime DateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				if(this._dateCreated != value)
				{
					this.OnPropertyChanging("DateCreated");
					this._dateCreated = value;
					this.OnPropertyChanged("DateCreated");
				}
			}
		}
		
		private IList<IdentityUserClaim> _identityUserClaims = new List<IdentityUserClaim>();
		[Collection(InverseProperty = "IdentityUser")]
		[Storage("_identityUserClaims")]
		public virtual IList<IdentityUserClaim> IdentityUserClaims
		{
			get
			{
				return this._identityUserClaims;
			}
		}
		
		private IList<IdentityUserInRole> _identityUserInRoles = new List<IdentityUserInRole>();
		[Collection(InverseProperty = "IdentityUser")]
		[Storage("_identityUserInRoles")]
		public virtual IList<IdentityUserInRole> IdentityUserInRoles
		{
			get
			{
				return this._identityUserInRoles;
			}
		}
		
		private IdentityUserLogin _identityUserLogin;
		[Reference(InverseProperty = "IdentityUser")]
		[Storage("_identityUserLogin")]
		public virtual IdentityUserLogin IdentityUserLogin
		{
			get
			{
				return this._identityUserLogin;
			}
			set
			{
				if(this._identityUserLogin != value)
				{
					this.OnPropertyChanging("IdentityUserLogin");
					this._identityUserLogin = value;
					this.OnPropertyChanged("IdentityUserLogin");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
