#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using Zakar.Models;

namespace Zakar.Models	
{
	[Table()]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Partner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private int _id;
		[Column(IsPrimaryKey = true)]
		[Storage("_id")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _title;
		[Storage("_title")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Title
		{
			get
			{
				return this._title;
			}
			set
			{
				if(this._title != value)
				{
					this.OnPropertyChanging("Title");
					this._title = value;
					this.OnPropertyChanged("Title");
				}
			}
		}
		
		private string _firstName;
		[Storage("_firstName")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string FirstName
		{
			get
			{
				return this._firstName;
			}
			set
			{
				if(this._firstName != value)
				{
					this.OnPropertyChanging("FirstName");
					this._firstName = value;
					this.OnPropertyChanged("FirstName");
				}
			}
		}
		
		private string _lastName;
		[Storage("_lastName")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string LastName
		{
			get
			{
				return this._lastName;
			}
			set
			{
				if(this._lastName != value)
				{
					this.OnPropertyChanging("LastName");
					this._lastName = value;
					this.OnPropertyChanged("LastName");
				}
			}
		}
		
		private string _email;
		[Storage("_email")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Email
		{
			get
			{
				return this._email;
			}
			set
			{
				if(this._email != value)
				{
					this.OnPropertyChanging("Email");
					this._email = value;
					this.OnPropertyChanged("Email");
				}
			}
		}
		
		private string _phone;
		[Storage("_phone")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if(this._phone != value)
				{
					this.OnPropertyChanging("Phone");
					this._phone = value;
					this.OnPropertyChanged("Phone");
				}
			}
		}
		
		private DateTime _dateCreated;
		[Storage("_dateCreated")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual DateTime DateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				if(this._dateCreated != value)
				{
					this.OnPropertyChanging("DateCreated");
					this._dateCreated = value;
					this.OnPropertyChanged("DateCreated");
				}
			}
		}
		
		private int _churchId;
		[Storage("_churchId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int ChurchId
		{
			get
			{
				return this._churchId;
			}
			set
			{
				if(this._churchId != value)
				{
					this.OnPropertyChanging("ChurchId");
					this._churchId = value;
					this.OnPropertyChanged("ChurchId");
				}
			}
		}
		
		private int? _pCFId;
		[Storage("_pCFId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int? PCFId
		{
			get
			{
				return this._pCFId;
			}
			set
			{
				if(this._pCFId != value)
				{
					this.OnPropertyChanging("PCFId");
					this._pCFId = value;
					this.OnPropertyChanged("PCFId");
				}
			}
		}
		
		private int? _cellId;
		[Storage("_cellId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int? CellId
		{
			get
			{
				return this._cellId;
			}
			set
			{
				if(this._cellId != value)
				{
					this.OnPropertyChanging("CellId");
					this._cellId = value;
					this.OnPropertyChanged("CellId");
				}
			}
		}
		
		private string _uniqueId;
		[Storage("_uniqueId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string UniqueId
		{
			get
			{
				return this._uniqueId;
			}
			set
			{
				if(this._uniqueId != value)
				{
					this.OnPropertyChanging("UniqueId");
					this._uniqueId = value;
					this.OnPropertyChanged("UniqueId");
				}
			}
		}
		
		private Church _church;
		[ForeignKeyAssociation(SharedFields = "ChurchId", TargetFields = "Id", IsManaged = true)]
		[Storage("_church")]
		public virtual Church Church
		{
			get
			{
				return this._church;
			}
			set
			{
				if(this._church != value)
				{
					this.OnPropertyChanging("Church");
					this._church = value;
					this.OnPropertyChanged("Church");
				}
			}
		}
		
		private IList<Partnership> _partnerships = new List<Partnership>();
		[Collection(InverseProperty = "Partner")]
		[Storage("_partnerships")]
		public virtual IList<Partnership> Partnerships
		{
			get
			{
				return this._partnerships;
			}
		}
		
		private IList<NonValidatedPartnershipRecord> _nonValidatedPartnershipRecords = new List<NonValidatedPartnershipRecord>();
		[Collection(InverseProperty = "Partner1")]
		[Storage("_nonValidatedPartnershipRecords")]
		public virtual IList<NonValidatedPartnershipRecord> NonValidatedPartnershipRecords
		{
			get
			{
				return this._nonValidatedPartnershipRecords;
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
