#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using Zakar.Models;

namespace Zakar.Models	
{
	[Table("Partnerships", SchemaName = "dbo", UpdateSchema = true)]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Partnership : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private int _id;
		[Column("Id", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_id")]
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private int _partnershipArmId;
		[Column("PartnershipArmId", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_partnershipArmId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int PartnershipArmId
		{
			get
			{
				return this._partnershipArmId;
			}
			set
			{
				if(this._partnershipArmId != value)
				{
					this.OnPropertyChanging("PartnershipArmId");
					this._partnershipArmId = value;
					this.OnPropertyChanged("PartnershipArmId");
				}
			}
		}
		
		private int _partnerId;
		[Column("PartnerId", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_partnerId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int PartnerId
		{
			get
			{
				return this._partnerId;
			}
			set
			{
				if(this._partnerId != value)
				{
					this.OnPropertyChanging("PartnerId");
					this._partnerId = value;
					this.OnPropertyChanged("PartnerId");
				}
			}
		}
		
		private decimal _amount;
		[Column("Amount", OpenAccessType = OpenAccessType.Decimal, Length = 18, Scale = 2, SqlType = "decimal")]
		[Storage("_amount")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual decimal Amount
		{
			get
			{
				return this._amount;
			}
			set
			{
				if(this._amount != value)
				{
					this.OnPropertyChanging("Amount");
					this._amount = value;
					this.OnPropertyChanged("Amount");
				}
			}
		}
		
		private int _month;
		[Column("Month", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_month")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Month
		{
			get
			{
				return this._month;
			}
			set
			{
				if(this._month != value)
				{
					this.OnPropertyChanging("Month");
					this._month = value;
					this.OnPropertyChanged("Month");
				}
			}
		}
		
		private int _year;
		[Column("Year", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_year")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Year
		{
			get
			{
				return this._year;
			}
			set
			{
				if(this._year != value)
				{
					this.OnPropertyChanging("Year");
					this._year = value;
					this.OnPropertyChanged("Year");
				}
			}
		}
		
		private int _currencyId;
		[Column("CurrencyId", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_currencyId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int CurrencyId
		{
			get
			{
				return this._currencyId;
			}
			set
			{
				if(this._currencyId != value)
				{
					this.OnPropertyChanging("CurrencyId");
					this._currencyId = value;
					this.OnPropertyChanged("CurrencyId");
				}
			}
		}
		
		private DateTime? _dateCreated;
		[Column("DateCreated", OpenAccessType = OpenAccessType.DateTime, IsNullable = true, Length = 0, Scale = 0, SqlType = "datetime")]
		[Storage("_dateCreated")]
		[System.ComponentModel.DataAnnotations.DataType(System.ComponentModel.DataAnnotations.DataType.DateTime)]
		public virtual DateTime? DateCreated
		{
			get
			{
				return this._dateCreated;
			}
			set
			{
				if(this._dateCreated != value)
				{
					this.OnPropertyChanging("DateCreated");
					this._dateCreated = value;
					this.OnPropertyChanged("DateCreated");
				}
			}
		}
		
		private PartnershipArm _partnershipArm;
		[ForeignKeyAssociation(ConstraintName = "FK_PartnershipArmPartnership", SharedFields = "PartnershipArmId", TargetFields = "Id")]
		[Storage("_partnershipArm")]
		public virtual PartnershipArm PartnershipArm
		{
			get
			{
				return this._partnershipArm;
			}
			set
			{
				if(this._partnershipArm != value)
				{
					this.OnPropertyChanging("PartnershipArm");
					this._partnershipArm = value;
					this.OnPropertyChanged("PartnershipArm");
				}
			}
		}
		
		private Partner _partner;
		[ForeignKeyAssociation(ConstraintName = "FK_PartnerPartnership", SharedFields = "PartnerId", TargetFields = "Id")]
		[Storage("_partner")]
		public virtual Partner Partner
		{
			get
			{
				return this._partner;
			}
			set
			{
				if(this._partner != value)
				{
					this.OnPropertyChanging("Partner");
					this._partner = value;
					this.OnPropertyChanged("Partner");
				}
			}
		}
		
		private Currency _currency;
		[ForeignKeyAssociation(ConstraintName = "FK_CurrencyPartnership", SharedFields = "CurrencyId", TargetFields = "Id")]
		[Storage("_currency")]
		public virtual Currency Currency
		{
			get
			{
				return this._currency;
			}
			set
			{
				if(this._currency != value)
				{
					this.OnPropertyChanging("Currency");
					this._currency = value;
					this.OnPropertyChanged("Currency");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
