#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using Zakar.Models;

namespace Zakar.Models	
{
	[Table(UpdateSchema = true)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class PCF : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private int _id;
		[Column(IsPrimaryKey = true)]
		[Storage("_id")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int Id
		{
			get
			{
				return this._id;
			}
			set
			{
				if(this._id != value)
				{
					this.OnPropertyChanging("Id");
					this._id = value;
					this.OnPropertyChanged("Id");
				}
			}
		}
		
		private string _uniqueId;
		[Storage("_uniqueId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string UniqueId
		{
			get
			{
				return this._uniqueId;
			}
			set
			{
				if(this._uniqueId != value)
				{
					this.OnPropertyChanging("UniqueId");
					this._uniqueId = value;
					this.OnPropertyChanged("UniqueId");
				}
			}
		}
		
		private string _name;
		[Storage("_name")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string Name
		{
			get
			{
				return this._name;
			}
			set
			{
				if(this._name != value)
				{
					this.OnPropertyChanging("Name");
					this._name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}
		
		private int _churchId;
		[Storage("_churchId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int ChurchId
		{
			get
			{
				return this._churchId;
			}
			set
			{
				if(this._churchId != value)
				{
					this.OnPropertyChanging("ChurchId");
					this._churchId = value;
					this.OnPropertyChanged("ChurchId");
				}
			}
		}
		
		private Church _church;
		[ForeignKeyAssociation(SharedFields = "ChurchId", TargetFields = "Id", IsManaged = true)]
		[Storage("_church")]
		public virtual Church Church
		{
			get
			{
				return this._church;
			}
			set
			{
				if(this._church != value)
				{
					this.OnPropertyChanging("Church");
					this._church = value;
					this.OnPropertyChanged("Church");
				}
			}
		}
		
		private IList<Cell> _cells = new List<Cell>();
		[Collection(InverseProperty = "PCF", Depend = true, IsManaged = true)]
		[Storage("_cells")]
		public virtual IList<Cell> Cells
		{
			get
			{
				return this._cells;
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
