#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;

namespace Zakar.Models	
{
	[Table("webpages_OAuthMembership", SchemaName = "dbo")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	public partial class Webpages_OAuthMembership : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private string _provider;
		[Column("Provider", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsPrimaryKey = true, Length = 30, Scale = 0, SqlType = "nvarchar")]
		[Storage("_provider")]
		[System.ComponentModel.DataAnnotations.StringLength(30)]
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual string Provider
		{
			get
			{
				return this._provider;
			}
			set
			{
				if(this._provider != value)
				{
					this.OnPropertyChanging("Provider");
					this._provider = value;
					this.OnPropertyChanged("Provider");
				}
			}
		}
		
		private string _providerUserId;
		[Column("ProviderUserId", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, IsPrimaryKey = true, Length = 100, Scale = 0, SqlType = "nvarchar")]
		[Storage("_providerUserId")]
		[System.ComponentModel.DataAnnotations.StringLength(100)]
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual string ProviderUserId
		{
			get
			{
				return this._providerUserId;
			}
			set
			{
				if(this._providerUserId != value)
				{
					this.OnPropertyChanging("ProviderUserId");
					this._providerUserId = value;
					this.OnPropertyChanged("ProviderUserId");
				}
			}
		}
		
		private int _userId;
		[Column("UserId", OpenAccessType = OpenAccessType.Int32, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_userId")]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual int UserId
		{
			get
			{
				return this._userId;
			}
			set
			{
				if(this._userId != value)
				{
					this.OnPropertyChanging("UserId");
					this._userId = value;
					this.OnPropertyChanged("UserId");
				}
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
