#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using System.ComponentModel;
using Zakar.Models;

namespace Zakar.Models	
{
	[Table("webpages_Roles", SchemaName = "dbo")]
	[ConcurrencyControl(OptimisticConcurrencyControlStrategy.Changed)]
	[KeyGenerator(KeyGenerator.Autoinc)]
	public partial class Webpages_Role : INotifyPropertyChanging, INotifyPropertyChanged
	{
		private int _roleId;
		[Column("RoleId", OpenAccessType = OpenAccessType.Int32, IsBackendCalculated = true, IsPrimaryKey = true, Length = 0, Scale = 0, SqlType = "int")]
		[Storage("_roleId")]
		[System.ComponentModel.DataAnnotations.Required()]
		[System.ComponentModel.DataAnnotations.Key()]
		public virtual int RoleId
		{
			get
			{
				return this._roleId;
			}
			set
			{
				if(this._roleId != value)
				{
					this.OnPropertyChanging("RoleId");
					this._roleId = value;
					this.OnPropertyChanged("RoleId");
				}
			}
		}
		
		private string _roleName;
		[Column("RoleName", OpenAccessType = OpenAccessType.UnicodeStringVariableLength, Length = 256, Scale = 0, SqlType = "nvarchar")]
		[Storage("_roleName")]
		[System.ComponentModel.DataAnnotations.StringLength(256)]
		[System.ComponentModel.DataAnnotations.Required()]
		public virtual string RoleName
		{
			get
			{
				return this._roleName;
			}
			set
			{
				if(this._roleName != value)
				{
					this.OnPropertyChanging("RoleName");
					this._roleName = value;
					this.OnPropertyChanged("RoleName");
				}
			}
		}
		
		private IList<UserProfile> _userProfiles = new List<UserProfile>();
		[Collection(InverseProperty = "Webpages_Roles")]
		[Storage("_userProfiles")]
		public virtual IList<UserProfile> UserProfiles
		{
			get
			{
				return this._userProfiles;
			}
		}
		
		#region INotifyPropertyChanging members
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		protected virtual void OnPropertyChanging(string propertyName)
		{
			if(this.PropertyChanging != null)
			{
				this.PropertyChanging(this, new PropertyChangingEventArgs(propertyName));
			}
		}
		
		#endregion
		
		#region INotifyPropertyChanged members
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void OnPropertyChanged(string propertyName)
		{
			if(this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		#endregion
		
	}
}
#pragma warning restore 1591
